// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Localizations {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        public static string CurrentDownloads {
            get {
                return ResourceManager.GetString("CurrentDownloads", resourceCulture);
            }
        }
        
        public static string EqualizerPresets {
            get {
                return ResourceManager.GetString("EqualizerPresets", resourceCulture);
            }
        }
        
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static string Equalizer {
            get {
                return ResourceManager.GetString("Equalizer", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string DefaultPreset {
            get {
                return ResourceManager.GetString("DefaultPreset", resourceCulture);
            }
        }
        
        public static string RenamePreset {
            get {
                return ResourceManager.GetString("RenamePreset", resourceCulture);
            }
        }
        
        public static string RenameError {
            get {
                return ResourceManager.GetString("RenameError", resourceCulture);
            }
        }
        
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        public static string CopyPreset {
            get {
                return ResourceManager.GetString("CopyPreset", resourceCulture);
            }
        }
        
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string SyncingDatabase {
            get {
                return ResourceManager.GetString("SyncingDatabase", resourceCulture);
            }
        }
        
        public static string WelcomToGmusic {
            get {
                return ResourceManager.GetString("WelcomToGmusic", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        public static string ThereWasAnErrorPlayingTrack {
            get {
                return ResourceManager.GetString("ThereWasAnErrorPlayingTrack", resourceCulture);
            }
        }
        
        public static string PlaylistName {
            get {
                return ResourceManager.GetString("PlaylistName", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        public static string RecentStations {
            get {
                return ResourceManager.GetString("RecentStations", resourceCulture);
            }
        }
        
        public static string MyStations {
            get {
                return ResourceManager.GetString("MyStations", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string CreatingStation {
            get {
                return ResourceManager.GetString("CreatingStation", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        public static string EnableLikeOnTheLockScreen {
            get {
                return ResourceManager.GetString("EnableLikeOnTheLockScreen", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        public static string AlbumArtist {
            get {
                return ResourceManager.GetString("AlbumArtist", resourceCulture);
            }
        }
        
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        public static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string EnableLikeHint {
            get {
                return ResourceManager.GetString("EnableLikeHint", resourceCulture);
            }
        }
        
        public static string EnableGaplessPlayback {
            get {
                return ResourceManager.GetString("EnableGaplessPlayback", resourceCulture);
            }
        }
        
        public static string EnableGapplessHint {
            get {
                return ResourceManager.GetString("EnableGapplessHint", resourceCulture);
            }
        }
        
        public static string PlayVideosWhenAvailable {
            get {
                return ResourceManager.GetString("PlayVideosWhenAvailable", resourceCulture);
            }
        }
        
        public static string PlaysMusicVideoHint {
            get {
                return ResourceManager.GetString("PlaysMusicVideoHint", resourceCulture);
            }
        }
        
        public static string PlayCleanVersionsOfSongs {
            get {
                return ResourceManager.GetString("PlayCleanVersionsOfSongs", resourceCulture);
            }
        }
        
        public static string PlayesCleanVersionOfSongsHint {
            get {
                return ResourceManager.GetString("PlayesCleanVersionOfSongsHint", resourceCulture);
            }
        }
        
        public static string Streaming {
            get {
                return ResourceManager.GetString("Streaming", resourceCulture);
            }
        }
        
        public static string DisableAllAccess {
            get {
                return ResourceManager.GetString("DisableAllAccess", resourceCulture);
            }
        }
        
        public static string DisableAllAccessHint {
            get {
                return ResourceManager.GetString("DisableAllAccessHint", resourceCulture);
            }
        }
        
        public static string CellularAudioQuality {
            get {
                return ResourceManager.GetString("CellularAudioQuality", resourceCulture);
            }
        }
        
        public static string WifiAudioQuality {
            get {
                return ResourceManager.GetString("WifiAudioQuality", resourceCulture);
            }
        }
        
        public static string VideoQuality {
            get {
                return ResourceManager.GetString("VideoQuality", resourceCulture);
            }
        }
        
        public static string OfflineAudioQuality {
            get {
                return ResourceManager.GetString("OfflineAudioQuality", resourceCulture);
            }
        }
        
        public static string QualityHints {
            get {
                return ResourceManager.GetString("QualityHints", resourceCulture);
            }
        }
        
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        public static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        public static string NobodyHasRatedYet {
            get {
                return ResourceManager.GetString("NobodyHasRatedYet", resourceCulture);
            }
        }
        
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        public static string ImportIPodMusic {
            get {
                return ResourceManager.GetString("ImportIPodMusic", resourceCulture);
            }
        }
        
        public static string ImportIpodHint {
            get {
                return ResourceManager.GetString("ImportIpodHint", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string ResyncDatabase {
            get {
                return ResourceManager.GetString("ResyncDatabase", resourceCulture);
            }
        }
        
        public static string ResyncDatabaseHint {
            get {
                return ResourceManager.GetString("ResyncDatabaseHint", resourceCulture);
            }
        }
        
        public static string DownloadQueue {
            get {
                return ResourceManager.GetString("DownloadQueue", resourceCulture);
            }
        }
        
        public static string SongsCount {
            get {
                return ResourceManager.GetString("SongsCount", resourceCulture);
            }
        }
        
        public static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        public static string ErrorLoggingInto {
            get {
                return ResourceManager.GetString("ErrorLoggingInto", resourceCulture);
            }
        }
        
        public static string OnlyOnePersonHasRatedThisVersion {
            get {
                return ResourceManager.GetString("OnlyOnePersonHasRatedThisVersion", resourceCulture);
            }
        }
        
        public static string Only {
            get {
                return ResourceManager.GetString("Only", resourceCulture);
            }
        }
        
        public static string PeopleHaveRatedThisVersion {
            get {
                return ResourceManager.GetString("PeopleHaveRatedThisVersion", resourceCulture);
            }
        }
        
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        public static string PleaseSendAnEmailTo {
            get {
                return ResourceManager.GetString("PleaseSendAnEmailTo", resourceCulture);
            }
        }
        
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        public static string YouShouldReceiveAReplyShortly_ {
            get {
                return ResourceManager.GetString("YouShouldReceiveAReplyShortly_", resourceCulture);
            }
        }
        
        public static string UsesLessData {
            get {
                return ResourceManager.GetString("UsesLessData", resourceCulture);
            }
        }
        
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        public static string UsesMoreData {
            get {
                return ResourceManager.GetString("UsesMoreData", resourceCulture);
            }
        }
        
        public static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Nevermind {
            get {
                return ResourceManager.GetString("Nevermind", resourceCulture);
            }
        }
        
        public static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        public static string AdditionalTracks {
            get {
                return ResourceManager.GetString("AdditionalTracks", resourceCulture);
            }
        }
        
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        public static string CurrentPlaylist {
            get {
                return ResourceManager.GetString("CurrentPlaylist", resourceCulture);
            }
        }
        
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        public static string StartingARadioStationWillDisableOfflineMode {
            get {
                return ResourceManager.GetString("StartingARadioStationWillDisableOfflineMode", resourceCulture);
            }
        }
        
        public static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
    }
}
