//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localizations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to Playlist.
        /// </summary>
        public static string AddingToPlaylist {
            get {
                return ResourceManager.GetString("AddingToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Tracks.
        /// </summary>
        public static string AdditionalTracks {
            get {
                return ResourceManager.GetString("AdditionalTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Streaming Service.
        /// </summary>
        public static string AddStreamingService {
            get {
                return ResourceManager.GetString("AddStreamingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Library.
        /// </summary>
        public static string AddToLibrary {
            get {
                return ResourceManager.GetString("AddToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string AddToPlaylist {
            get {
                return ResourceManager.GetString("AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string AddToQueue {
            get {
                return ResourceManager.GetString("AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Artist.
        /// </summary>
        public static string AlbumArtist {
            get {
                return ResourceManager.GetString("AlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Tweet.
        /// </summary>
        public static string AutoTweet {
            get {
                return ResourceManager.GetString("AutoTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular Audio Quality.
        /// </summary>
        public static string CellularAudioQuality {
            get {
                return ResourceManager.GetString("CellularAudioQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Preset.
        /// </summary>
        public static string CopyPreset {
            get {
                return ResourceManager.GetString("CopyPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Station.
        /// </summary>
        public static string CreatingStation {
            get {
                return ResourceManager.GetString("CreatingStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Downloads.
        /// </summary>
        public static string CurrentDownloads {
            get {
                return ResourceManager.GetString("CurrentDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Playlist.
        /// </summary>
        public static string CurrentPlaylist {
            get {
                return ResourceManager.GetString("CurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Preset.
        /// </summary>
        public static string DefaultPreset {
            get {
                return ResourceManager.GetString("DefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All Access.
        /// </summary>
        public static string DisableAllAccess {
            get {
                return ResourceManager.GetString("DisableAllAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable if you do not have all access integration.
        /// </summary>
        public static string DisableAllAccessHint {
            get {
                return ResourceManager.GetString("DisableAllAccessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Queue.
        /// </summary>
        public static string DownloadQueue {
            get {
                return ResourceManager.GetString("DownloadQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Gapless playback.
        /// </summary>
        public static string EnableGaplessPlayback {
            get {
                return ResourceManager.GetString("EnableGaplessPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This removes the silence from the last few seconds of a song and starts the next one.
        /// </summary>
        public static string EnableGapplessHint {
            get {
                return ResourceManager.GetString("EnableGapplessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this is enabled, the previous button is replaced by Like/Dislike buttons. (iOS 7.1 and higher).
        /// </summary>
        public static string EnableLikeHint {
            get {
                return ResourceManager.GetString("EnableLikeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Like on the lock screen.
        /// </summary>
        public static string EnableLikeOnTheLockScreen {
            get {
                return ResourceManager.GetString("EnableLikeOnTheLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer.
        /// </summary>
        public static string Equalizer {
            get {
                return ResourceManager.GetString("Equalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer Presets.
        /// </summary>
        public static string EqualizerPresets {
            get {
                return ResourceManager.GetString("EqualizerPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding to playlist.
        /// </summary>
        public static string ErrorAddingToPlaylist {
            get {
                return ResourceManager.GetString("ErrorAddingToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the radio station.
        /// </summary>
        public static string ErrorCreatingStation {
            get {
                return ResourceManager.GetString("ErrorCreatingStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging into.
        /// </summary>
        public static string ErrorLoggingInto {
            get {
                return ResourceManager.GetString("ErrorLoggingInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Album.
        /// </summary>
        public static string GoToAlbum {
            get {
                return ResourceManager.GetString("GoToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Artist.
        /// </summary>
        public static string GoToArtist {
            get {
                return ResourceManager.GetString("GoToArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Feeling Lucky.
        /// </summary>
        public static string ImFeelingLuckyRadioStation {
            get {
                return ResourceManager.GetString("ImFeelingLuckyRadioStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically imports and plays music from your local library. This saves data and space on your phone..
        /// </summary>
        public static string ImportIpodHint {
            get {
                return ResourceManager.GetString("ImportIpodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import iPod Music.
        /// </summary>
        public static string ImportIPodMusic {
            get {
                return ResourceManager.GetString("ImportIPodMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Out.
        /// </summary>
        public static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string LogOutConfirmation {
            get {
                return ResourceManager.GetString("LogOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my music.
        /// </summary>
        public static string MusicLibraryHeading {
            get {
                return ResourceManager.GetString("MusicLibraryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stations.
        /// </summary>
        public static string MyStations {
            get {
                return ResourceManager.GetString("MyStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevermind.
        /// </summary>
        public static string Nevermind {
            get {
                return ResourceManager.GetString("Nevermind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Preset.
        /// </summary>
        public static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has rated yet :(.
        /// </summary>
        public static string NobodyHasRatedYet {
            get {
                return ResourceManager.GetString("NobodyHasRatedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Audio Quality.
        /// </summary>
        public static string OfflineAudioQuality {
            get {
                return ResourceManager.GetString("OfflineAudioQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Only.
        /// </summary>
        public static string OfflineOnly {
            get {
                return ResourceManager.GetString("OfflineOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only.
        /// </summary>
        public static string Only {
            get {
                return ResourceManager.GetString("Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 person has rated this version.
        /// </summary>
        public static string OnlyOnePersonHasRatedThisVersion {
            get {
                return ResourceManager.GetString("OnlyOnePersonHasRatedThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people have rated this version.
        /// </summary>
        public static string PeopleHaveRatedThisVersion {
            get {
                return ResourceManager.GetString("PeopleHaveRatedThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play clean versions of songs.
        /// </summary>
        public static string PlayCleanVersionsOfSongs {
            get {
                return ResourceManager.GetString("PlayCleanVersionsOfSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays clean versions of songs during Radio Playback when available..
        /// </summary>
        public static string PlayesCleanVersionOfSongsHint {
            get {
                return ResourceManager.GetString("PlayesCleanVersionOfSongsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name.
        /// </summary>
        public static string PlaylistName {
            get {
                return ResourceManager.GetString("PlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Next.
        /// </summary>
        public static string PlayNext {
            get {
                return ResourceManager.GetString("PlayNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays the music video instead of the song when a music video is available..
        /// </summary>
        public static string PlaysMusicVideoHint {
            get {
                return ResourceManager.GetString("PlaysMusicVideoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Video.
        /// </summary>
        public static string PlayVideo {
            get {
                return ResourceManager.GetString("PlayVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play videos when available.
        /// </summary>
        public static string PlayVideosWhenAvailable {
            get {
                return ResourceManager.GetString("PlayVideosWhenAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate.
        /// </summary>
        public static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send an email to.
        /// </summary>
        public static string PleaseSendAnEmailTo {
            get {
                return ResourceManager.GetString("PleaseSendAnEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        public static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later.
        /// </summary>
        public static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are having issues with buffering or skipping try lowering the stream quality. Lower stream qualities use less data and take less space to store on the device..
        /// </summary>
        public static string QualityHints {
            get {
                return ResourceManager.GetString("QualityHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        public static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Stations.
        /// </summary>
        public static string RecentStations {
            get {
                return ResourceManager.GetString("RecentStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Device.
        /// </summary>
        public static string RemoveFromDevice {
            get {
                return ResourceManager.GetString("RemoveFromDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Library.
        /// </summary>
        public static string RemoveFromLibrary {
            get {
                return ResourceManager.GetString("RemoveFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string RenameError {
            get {
                return ResourceManager.GetString("RenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Preset.
        /// </summary>
        public static string RenamePreset {
            get {
                return ResourceManager.GetString("RenamePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resync Database.
        /// </summary>
        public static string ResyncDatabase {
            get {
                return ResourceManager.GetString("ResyncDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the database and do a full sync from the server..
        /// </summary>
        public static string ResyncDatabaseHint {
            get {
                return ResourceManager.GetString("ResyncDatabaseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs Count.
        /// </summary>
        public static string SongsCount {
            get {
                return ResourceManager.GetString("SongsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a radio station will disable offline mode..
        /// </summary>
        public static string StartingARadioStationWillDisableOfflineMode {
            get {
                return ResourceManager.GetString("StartingARadioStationWillDisableOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting station.
        /// </summary>
        public static string StartingStation {
            get {
                return ResourceManager.GetString("StartingStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Radio Station.
        /// </summary>
        public static string StartRadioStation {
            get {
                return ResourceManager.GetString("StartRadioStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        public static string Streaming {
            get {
                return ResourceManager.GetString("Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing Database.
        /// </summary>
        public static string SyncingDatabase {
            get {
                return ResourceManager.GetString("SyncingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error playing this track.
        /// </summary>
        public static string ThereWasAnErrorPlayingTrack {
            get {
                return ResourceManager.GetString("ThereWasAnErrorPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Number.
        /// </summary>
        public static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (uses less data).
        /// </summary>
        public static string UsesLessData {
            get {
                return ResourceManager.GetString("UsesLessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (uses more data).
        /// </summary>
        public static string UsesMoreData {
            get {
                return ResourceManager.GetString("UsesMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Quality.
        /// </summary>
        public static string VideoQuality {
            get {
                return ResourceManager.GetString("VideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to
        ///gMusic.
        /// </summary>
        public static string WelcomToGmusic {
            get {
                return ResourceManager.GetString("WelcomToGmusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Audio Quality.
        /// </summary>
        public static string WifiAudioQuality {
            get {
                return ResourceManager.GetString("WifiAudioQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should receive a reply shortly..
        /// </summary>
        public static string YouShouldReceiveAReplyShortly_ {
            get {
                return ResourceManager.GetString("YouShouldReceiveAReplyShortly_", resourceCulture);
            }
        }
    }
}
