// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.6.57.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Localizations {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_it {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_it() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Localizations.Strings.it", typeof(Strings_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        internal static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        internal static string CurrentDownloads {
            get {
                return ResourceManager.GetString("CurrentDownloads", resourceCulture);
            }
        }
        
        internal static string EqualizerPresets {
            get {
                return ResourceManager.GetString("EqualizerPresets", resourceCulture);
            }
        }
        
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        internal static string Equalizer {
            get {
                return ResourceManager.GetString("Equalizer", resourceCulture);
            }
        }
        
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        internal static string DefaultPreset {
            get {
                return ResourceManager.GetString("DefaultPreset", resourceCulture);
            }
        }
        
        internal static string RenamePreset {
            get {
                return ResourceManager.GetString("RenamePreset", resourceCulture);
            }
        }
        
        internal static string RenameError {
            get {
                return ResourceManager.GetString("RenameError", resourceCulture);
            }
        }
        
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        internal static string CopyPreset {
            get {
                return ResourceManager.GetString("CopyPreset", resourceCulture);
            }
        }
        
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string SyncingDatabase {
            get {
                return ResourceManager.GetString("SyncingDatabase", resourceCulture);
            }
        }
        
        internal static string WelcomToGmusic {
            get {
                return ResourceManager.GetString("WelcomToGmusic", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        internal static string ThereWasAnErrorPlayingTrack {
            get {
                return ResourceManager.GetString("ThereWasAnErrorPlayingTrack", resourceCulture);
            }
        }
        
        internal static string PlaylistName {
            get {
                return ResourceManager.GetString("PlaylistName", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        internal static string RecentStations {
            get {
                return ResourceManager.GetString("RecentStations", resourceCulture);
            }
        }
        
        internal static string MyStations {
            get {
                return ResourceManager.GetString("MyStations", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string CreatingStation {
            get {
                return ResourceManager.GetString("CreatingStation", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        internal static string EnableLikeOnTheLockScreen {
            get {
                return ResourceManager.GetString("EnableLikeOnTheLockScreen", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        internal static string AlbumArtist {
            get {
                return ResourceManager.GetString("AlbumArtist", resourceCulture);
            }
        }
        
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        internal static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        internal static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        internal static string EnableLikeHint {
            get {
                return ResourceManager.GetString("EnableLikeHint", resourceCulture);
            }
        }
        
        internal static string EnableGaplessPlayback {
            get {
                return ResourceManager.GetString("EnableGaplessPlayback", resourceCulture);
            }
        }
        
        internal static string EnableGapplessHint {
            get {
                return ResourceManager.GetString("EnableGapplessHint", resourceCulture);
            }
        }
        
        internal static string PlayVideosWhenAvailable {
            get {
                return ResourceManager.GetString("PlayVideosWhenAvailable", resourceCulture);
            }
        }
        
        internal static string PlaysMusicVideoHint {
            get {
                return ResourceManager.GetString("PlaysMusicVideoHint", resourceCulture);
            }
        }
        
        internal static string PlayCleanVersionsOfSongs {
            get {
                return ResourceManager.GetString("PlayCleanVersionsOfSongs", resourceCulture);
            }
        }
        
        internal static string PlayesCleanVersionOfSongsHint {
            get {
                return ResourceManager.GetString("PlayesCleanVersionOfSongsHint", resourceCulture);
            }
        }
        
        internal static string Streaming {
            get {
                return ResourceManager.GetString("Streaming", resourceCulture);
            }
        }
        
        internal static string DisableAllAccess {
            get {
                return ResourceManager.GetString("DisableAllAccess", resourceCulture);
            }
        }
        
        internal static string DisableAllAccessHint {
            get {
                return ResourceManager.GetString("DisableAllAccessHint", resourceCulture);
            }
        }
        
        internal static string CellularAudioQuality {
            get {
                return ResourceManager.GetString("CellularAudioQuality", resourceCulture);
            }
        }
        
        internal static string WifiAudioQuality {
            get {
                return ResourceManager.GetString("WifiAudioQuality", resourceCulture);
            }
        }
        
        internal static string VideoQuality {
            get {
                return ResourceManager.GetString("VideoQuality", resourceCulture);
            }
        }
        
        internal static string OfflineAudioQuality {
            get {
                return ResourceManager.GetString("OfflineAudioQuality", resourceCulture);
            }
        }
        
        internal static string QualityHints {
            get {
                return ResourceManager.GetString("QualityHints", resourceCulture);
            }
        }
        
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        internal static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        internal static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        internal static string NobodyHasRatedYet {
            get {
                return ResourceManager.GetString("NobodyHasRatedYet", resourceCulture);
            }
        }
        
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        internal static string ImportIPodMusic {
            get {
                return ResourceManager.GetString("ImportIPodMusic", resourceCulture);
            }
        }
        
        internal static string ImportIpodHint {
            get {
                return ResourceManager.GetString("ImportIpodHint", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string ResyncDatabase {
            get {
                return ResourceManager.GetString("ResyncDatabase", resourceCulture);
            }
        }
        
        internal static string ResyncDatabaseHint {
            get {
                return ResourceManager.GetString("ResyncDatabaseHint", resourceCulture);
            }
        }
        
        internal static string DownloadQueue {
            get {
                return ResourceManager.GetString("DownloadQueue", resourceCulture);
            }
        }
        
        internal static string SongsCount {
            get {
                return ResourceManager.GetString("SongsCount", resourceCulture);
            }
        }
        
        internal static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        internal static string ErrorLoggingInto {
            get {
                return ResourceManager.GetString("ErrorLoggingInto", resourceCulture);
            }
        }
        
        internal static string OnlyOnePersonHasRatedThisVersion {
            get {
                return ResourceManager.GetString("OnlyOnePersonHasRatedThisVersion", resourceCulture);
            }
        }
        
        internal static string Only {
            get {
                return ResourceManager.GetString("Only", resourceCulture);
            }
        }
        
        internal static string PeopleHaveRatedThisVersion {
            get {
                return ResourceManager.GetString("PeopleHaveRatedThisVersion", resourceCulture);
            }
        }
        
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        internal static string PleaseSendAnEmailTo {
            get {
                return ResourceManager.GetString("PleaseSendAnEmailTo", resourceCulture);
            }
        }
        
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        internal static string YouShouldReceiveAReplyShortly_ {
            get {
                return ResourceManager.GetString("YouShouldReceiveAReplyShortly_", resourceCulture);
            }
        }
        
        internal static string UsesLessData {
            get {
                return ResourceManager.GetString("UsesLessData", resourceCulture);
            }
        }
        
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        internal static string UsesMoreData {
            get {
                return ResourceManager.GetString("UsesMoreData", resourceCulture);
            }
        }
        
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string Nevermind {
            get {
                return ResourceManager.GetString("Nevermind", resourceCulture);
            }
        }
        
        internal static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        internal static string AdditionalTracks {
            get {
                return ResourceManager.GetString("AdditionalTracks", resourceCulture);
            }
        }
        
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        internal static string CurrentPlaylist {
            get {
                return ResourceManager.GetString("CurrentPlaylist", resourceCulture);
            }
        }
        
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        internal static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        internal static string StartingARadioStationWillDisableOfflineMode {
            get {
                return ResourceManager.GetString("StartingARadioStationWillDisableOfflineMode", resourceCulture);
            }
        }
        
        internal static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
    }
}
