// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MusicPlayer
{
	public partial class BottomView : NSView
	{
		public BottomView (IntPtr handle) : base (handle)
		{
		}
	}
}
