// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MusicPlayer
{
	public partial class CollectionView : NSScrollView
	{
		public CollectionView (IntPtr handle) : base (handle)
		{
		}
		[Export("initWithCoder:")]
		public CollectionView (NSCoder coder) : base (coder)
		{

		}
	}
}
