// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;

namespace MusicPlayer
{
	public partial class MainWindowView : NSView
	{
		NSView bottomView;
		NSSplitView topView;
		public MainWindowView (IntPtr handle) : base (handle)
		{
			bottomView = Subviews.First (x => x.Identifier == "PlaybackBar");
			bottomView.AddSubview(new PlaybackBar(bottomView.Bounds));
			topView = Subviews.OfType<NSSplitView> ().First ();
			LayoutSubviews ();
		}
		public override void ResizeSubviewsWithOldSize (CoreGraphics.CGSize oldSize)
		{
			base.ResizeSubviewsWithOldSize (oldSize);
			LayoutSubviews ();
		}

		const float bottomHeight = 67;
		void LayoutSubviews()
		{
			var bounds = Bounds;
			var frame = bounds;
			frame.Height = bottomHeight;
			bottomView.Frame = frame;

			frame.Y = frame.Bottom;
			frame.Height = bounds.Height - frame.Y;
			topView.Frame = frame;

		}
	}
}
