// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MusicPlayer.Managers;

namespace MusicPlayer
{
	public partial class MainWindow : NSWindow
	{
		public MainWindow (IntPtr handle) : base (handle)
		{
	
		}
		public override void SendEvent (NSEvent theEvent)
		{
			base.SendEvent (theEvent);
		}
		public override void BecomeMainWindow ()
		{
			base.BecomeMainWindow ();
		}
	}
}
